# config/services.yaml
parameters:
    shift4.base_url: '%env(SHIFT4_BASE_URL)%'
    shift4.api_key: '%env(SHIFT4_API_KEY)%'

    # ACI Payment Gateway Parameters
    aci.entity_id: '%env(ACI_ENTITY_ID)%'
    aci.api_key: '%env(ACI_API_KEY)%'

services:
    # Default settings for all services
    _defaults:
        autowire: true        # Automatically injects dependencies
        autoconfigure: true   # Automatically registers services as commands, event subscribers, etc.
        public: false         # Services are private by default

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Automatically tag all services implementing PaymentGatewayInterface
    _instanceof:
        App\PaymentGateway\PaymentGatewayInterface:
            tags: ['app.payment_gateway']

    # Autoload all services in src/PaymentGateway/
    App\PaymentGateway\:
        resource: '../src/PaymentGateway/'
        # Exclude abstract classes if any
        exclude: '../src/PaymentGateway/AbstractPaymentGateway.php'

    # Explicitly define Shift4Gateway service with injected parameters
    App\PaymentGateway\Shift4Gateway:
        arguments:
            $client: '@http_client'
            $baseUrl: '%shift4.base_url%'
            $apiKey: '%shift4.api_key%'
        tags: ['app.payment_gateway']

    # Explicitly define ACIGateway service with injected parameters
    App\PaymentGateway\ACIGateway:
        arguments:
            $client: '@http_client'
            $logger: '@logger'
            $entityId: '%aci.entity_id%'
            $apiKey: '%aci.api_key%'
        tags: ['app.payment_gateway']

    # Explicitly define PaymentProcessor and inject tagged services
    App\Service\PaymentProcessor:
        arguments:
            $gateways: !tagged_iterator app.payment_gateway